### ISSUE TITLE
Register sub-classed factories as instance fixtures?

### ISSUE THREAD

**Issue by pydolan** [pytest-dev/pytest-factoryboy#20]
Given the following factories:

```python
class BookFactory(factory.django.DjangoModelFactory):
    title = factory.LazyAttribute(lambda x: faker.sentence(nb_words=4))
    pub_date = factory.LazyAttribute(lambda x: faker.date())

    class Meta:
        model = Book

    author = factory.SubFactory(AuthorFactory)

class RedBookFactory(BookFactory):
    pass

class NovelFactory(BookFactory):
    pass
```

I was a bit confused at first as to why `red_book` and `novel` fixtures were not being created, but after looking at the code, it looks like the factory's model drives these instance fixtures.

Any interest in creating these fixtures?  If not, what's the reasoning? 

If anything, maybe add this example to the documentation, showing that the factory fixtures register (`red_book_factory` and `novel_factory`) but not the instance fixtures (`red_book` and `novel`).

**Comment by olegpidsadnyi** [comment]
You can work that around by specifying a concrete name during registration. I'll look into that! Or @pydolan , do you want to make a PR?

**Comment by olegpidsadnyi** [comment]
@pydolan Actually RedBook sounds like a flavor, which I'm really against.
NovelBook sounds more appropriate in case of polymorphic model. I'm handling polymorphism a bit different. I register base class factory with all possible fields of all subclasses plus the type discriminator field.
Since these factories will turn into dependency injection you won't longer care about certain subclass in your test. You will simply choose the type of book you want to have.
Lets say you want a red novel:

.. code:: python

    @pytest.mark.parametrize("book__type", ["novel"])
    @pytest.mark.parametrize("book__color", ["red"])
    def test_red_novel(book):
         assert book.color == "red"
         assert isinstance(book, Novel)


The thing is if you are implementing functional tests or any kind of fixture, test, whatever intermediate step using dependency injection you can't simply fork every single fixture and BDD step to support each flavor. Instead you should always use the principal fixture name and use parametrization a lot.

You can read more about flavors and ideas behind pytest-factoryboy in my article:
http://developer.paylogic.com/articles/factory-injection-combining-pytest-factory_boy.html

**Comment by pydolan** [comment]
The parameterization makes sense. I'll do that for my use case.  It might be good to throw a comment about, along with a link to your article, in docs in case others run into similar confusion. Thanks for your help!
