### ISSUE TITLE
scope of fixtures created by register()?

### ISSUE THREAD

**Issue by pouledodue** [pytest-dev/pytest-factoryboy#31]
when I do

```
register(AuthorFactory)
```

it creates fixture `author_factory`

my question is how can I specify a `scope='session'` to the fixture ?

**Comment by olegpidsadnyi** [comment]
currently not supported. I was never using model fixtures with the session scope because the entities of the data model are changed frequently.
For example author is not just one per your testing suite, right?
It is better for the test isolation to create new parents for every test.

Can you give me an example when author can be one for the whole session?

**Comment by NeveHanter** [comment]
Hey @olegpidsadnyi

I also want to suggest this change, in my case I have thousand of tests, nearly all of them need to create base DB structure consisting of approx. 60 db objects and because of the function scope each test creates these objects over and over only to delete them after the each of the tests completes.

Other case includes that each test case class have some objects which are common to each of it's test methods, so again we're creating same db objects and again we're deleting them between the tests.

**Comment by olegpidsadnyi** [comment]
@NeveHanter We are not deleting the objects from our database and it is huge. This also improves your tests in terms of isolation, so that you don't get false positives or irrelevant items don't appear in collections.
I'm not also sure if you can register some fixtures as session scoped. Can session scoped fixture depend on non-session scoped? In case of relationships you can easily configure such inconsistent dependencies.

**Comment by nathanielobrown** [comment]
@olegpidsadnyi, this would be useful for another simple (but important) reason. You cannot use a factory in a fixture with scope other than `function`. If you do, you get an error like `You tried to access the 'function' scoped fixture 'factory' with a 'class' scoped request object`.

I think it would be best to give people the option. If they are messing with scopes, ideally they understand what they are doing and the potential foot-guns that come with that.

Not a big deal as we can always use the factory directly in these cases, but would be nice to have this.

**Comment by czwartaoslpoj** [comment]
I'm quite surprised it is still not supported. I'm migrating Django project from unittest to pytest framework and this is big disadvantage. With big projects when you have factories that have subfactories that have subfactories, tests are slowing down drastically...

**Comment by youtux** [comment]
I think we can have this feature, but unfortunately, neither @olegpidsadnyi nor I have much spare time to address this.
Feel free to open a PR.
